In [8]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\astri\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\astri\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\astri\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\astri\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\astri\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd
#pip install openpyxl para que lea Excel

In [5]:
clientes = pd.read_excel("Clientes.xlsx")

In [6]:
ventas = pd.read_excel("Ventastaller.xlsx")

Mini reto
Usa la base de datos de ventas y responde

Preguntas:

Mostrar las primeras 10 filas.
Cuántas filas tiene?
Mostrar solo las columnas:
Producto
Precio
Mostrar únicamente productos mayores a $100.000.
Crear una columna Precio Final.
Mostrar únicamente productos de laptop.

In [9]:
ventas.head (10)

,ID_Venta,Fecha,Cliente,Ciudad,Producto,Categoría,Cantidad,Precio_Unitario,Estado
0,V001,2026-01-01,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado
1,V002,2026-01-02,Carlos Gómez,pereira,Mouse,tecnologia,5.0,85000,completado
2,V003,2026-01-03,María Díaz,PEREIRA,Teclado,Tecnología,3.0,120000,COMPLETADO
3,V004,2026-01-04,Juan López,Bogotá,Monitor,tecnologia,1.0,850000,Pendiente
4,V005,2026-01-05,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado
5,V006,2026-01-06,Pedro Ruiz,Medellín,Mouse,Tecnología,10.0,85000,Completado
6,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado
7,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado
8,V008,2026-01-08,Sofía Castro,Cali,Teclado,TECNOLOGIA,4.0,120000,Completado
9,V009,2026-01-09,Andrés Rojas,Cali,Monitor,Tecnología,NaN,850000,Pendiente

In [ ]:
ventas.shape

(51, 9)

In [12]:
ventas [["Producto","Precio_Unitario"]]

   Producto  Precio_Unitario
0    Laptop          2500000
1     Mouse            85000
2   Teclado           120000
3   Monitor           850000
4    Laptop          2500000
5     Mouse            85000
6    Laptop          2500000
7    Laptop          2500000
8   Teclado           120000
9   Monitor           850000
10   Laptop          2500000
11    Mouse            85000
12  Teclado           120000
13  Monitor           850000
14   Laptop          2500000
15    Mouse            85000
16  Teclado           120000
17  Monitor           850000
18   Laptop          2500000
19    Mouse            85000
20  Teclado           120000
21  Monitor           850000
22   Laptop          2500000
23    Mouse            85000
24  Monitor           850000
25   Laptop          2500000
26  Teclado           120000
27    Mouse            85000
28  Monitor           850000
29   Laptop          2500000
30    Mouse            85000
31  Teclado           120000
32   Laptop          2500000
33  Monitor           850000
34    Mouse            85000
35   Laptop          2500000
36  Teclado           120000
37  Monitor           850000
38   Laptop          2500000
39    Mouse            85000
40  Teclado           120000
41  Monitor           850000
42   Laptop          2500000
43    Mouse            85000
44  Teclado           120000
45  Monitor           850000
46   Laptop          2500000
47    Mouse            85000
48  Teclado           120000
49  Monitor           850000
50   Laptop          2500000

In [16]:
ventas [ventas["Precio_Unitario"]> 100000]

,ID_Venta,Fecha,Cliente,Ciudad,Producto,Categoría,Cantidad,Precio_Unitario,Estado
0,V001,2026-01-01,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado
2,V003,2026-01-03,María Díaz,PEREIRA,Teclado,Tecnología,3.0,120000,COMPLETADO
3,V004,2026-01-04,Juan López,Bogotá,Monitor,tecnologia,1.0,850000,Pendiente
4,V005,2026-01-05,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado
6,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado
7,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado
8,V008,2026-01-08,Sofía Castro,Cali,Teclado,TECNOLOGIA,4.0,120000,Completado
9,V009,2026-01-09,Andrés Rojas,Cali,Monitor,Tecnología,NaN,850000,Pendiente
10,V010,2026-01-10,Natalia Díaz,Bogotá,Laptop,Tecnología,1.0,2500000,Completado
12,V012,2026-01-12,Camila Soto,Pereira,Teclado,Tecnología,2.0,120000,completado
13,V013,2026-01-13,Daniel Vargas,Pereira,Monitor,tecnologia,2.0,850000,Completado
14,V014,2026-01-14,Valentina Cruz,PEREIRA,Laptop,Tecnología,1.0,2500000,Pendiente
16,V016,2026-01-16,Laura Torres,bogota,Teclado,TECNOLOGIA,3.0,120000,completado
17,V017,2026-01-17,Pedro Ruiz,Medellín,Monitor,Tecnologia,1.0,850000,Completado
18,V018,2026-01-18,Sofía Castro,Cali,Laptop,Tecnología,2.0,2500000,Completado
20,V020,2026-01-20,Ana Pérez,Pereira,Teclado,tecnologia,5.0,120000,Completado
21,V021,2026-01-21,Carlos Gómez,pereira,Monitor,Tecnología,2.0,850000,Completado
22,V022,2026-01-22,María Díaz,PEREIRA,Laptop,Tecnología,1.0,2500000,COMPLETADO
24,V024,2026-01-24,Laura Torres,bogota,Monitor,Tecnología,1.0,850000,Completado
25,V025,2026-01-25,Pedro Ruiz,Medellín,Laptop,Tecnología,2.0,2500000,Completado
26,V026,2026-01-26,Sofía Castro,Cali,Teclado,TECNOLOGIA,4.0,120000,Completado
28,V028,2026-01-28,Felipe Mora,Medellín,Monitor,Tecnología,2.0,850000,Pendiente
29,V029,2026-01-29,Camila Soto,Pereira,Laptop,tecnologia,1.0,2500000,Completado
31,V031,2026-01-31,Valentina Cruz,PEREIRA,Teclado,TECNOLOGIA,2.0,120000,Completado
32,V032,2026-02-01,Andrés Rojas,Cali,Laptop,Tecnología,1.0,2500000,Pendiente
33,V033,2026-02-02,Ana Pérez,Pereira,Monitor,tecnologia,2.0,850000,Completado
35,V035,2026-02-04,María Díaz,PEREIRA,Laptop,Tecnología,1.0,2500000,COMPLETADO
36,V036,2026-02-05,Juan López,Bogotá,Teclado,tecnologia,3.0,120000,Pendiente
37,V037,2026-02-06,Laura Torres,bogota,Monitor,Tecnología,1.0,850000,Completado
38,V038,2026-02-07,Pedro Ruiz,Medellín,Laptop,Tecnología,2.0,2500000,Completado
40,V040,2026-02-09,Natalia Díaz,Bogotá,Teclado,Tecnologia,2.0,120000,completado
41,V041,2026-02-10,Felipe Mora,Medellín,Monitor,Tecnología,1.0,850000,Pendiente
42,V042,2026-02-11,Camila Soto,Pereira,Laptop,tecnologia,1.0,2500000,Completado
44,V044,2026-02-13,Valentina Cruz,PEREIRA,Teclado,TECNOLOGIA,3.0,120000,Completado
45,V045,2026-02-14,Andrés Rojas,Cali,Monitor,Tecnología,2.0,850000,Pendiente
46,V046,2026-02-15,Ana Pérez,Pereira,Laptop,Tecnología,1.0,2500000,Completado
48,V048,2026-02-17,María Díaz,PEREIRA,Teclado,Tecnología,2.0,120000,COMPLETADO
49,V049,2026-02-18,Juan López,Bogotá,Monitor,tecnologia,1.0,850000,Pendiente
50,V050,2026-02-19,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado

In [19]:
ventas["Precio_Final"] = ventas["Precio_Unitario"] *0.19
ventas.head()

,ID_Venta,Fecha,Cliente,Ciudad,Producto,Categoría,Cantidad,Precio_Unitario,Estado,Precio_Final
0,V001,2026-01-01,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0
1,V002,2026-01-02,Carlos Gómez,pereira,Mouse,tecnologia,5.0,85000,completado,16150.0
2,V003,2026-01-03,María Díaz,PEREIRA,Teclado,Tecnología,3.0,120000,COMPLETADO,22800.0
3,V004,2026-01-04,Juan López,Bogotá,Monitor,tecnologia,1.0,850000,Pendiente,161500.0
4,V005,2026-01-05,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado,475000.0

In [21]:
ventas [ventas["Producto"] == "Laptop"]

,ID_Venta,Fecha,Cliente,Ciudad,Producto,Categoría,Cantidad,Precio_Unitario,Estado,Precio_Final
0,V001,2026-01-01,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0
4,V005,2026-01-05,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado,475000.0
6,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0
7,V007,2026-01-07,Ana Pérez,Pereira,Laptop,Tecnología,2.0,2500000,Completado,475000.0
10,V010,2026-01-10,Natalia Díaz,Bogotá,Laptop,Tecnología,1.0,2500000,Completado,475000.0
14,V014,2026-01-14,Valentina Cruz,PEREIRA,Laptop,Tecnología,1.0,2500000,Pendiente,475000.0
18,V018,2026-01-18,Sofía Castro,Cali,Laptop,Tecnología,2.0,2500000,Completado,475000.0
22,V022,2026-01-22,María Díaz,PEREIRA,Laptop,Tecnología,1.0,2500000,COMPLETADO,475000.0
25,V025,2026-01-25,Pedro Ruiz,Medellín,Laptop,Tecnología,2.0,2500000,Completado,475000.0
29,V029,2026-01-29,Camila Soto,Pereira,Laptop,tecnologia,1.0,2500000,Completado,475000.0
32,V032,2026-02-01,Andrés Rojas,Cali,Laptop,Tecnología,1.0,2500000,Pendiente,475000.0
35,V035,2026-02-04,María Díaz,PEREIRA,Laptop,Tecnología,1.0,2500000,COMPLETADO,475000.0
38,V038,2026-02-07,Pedro Ruiz,Medellín,Laptop,Tecnología,2.0,2500000,Completado,475000.0
42,V042,2026-02-11,Camila Soto,Pereira,Laptop,tecnologia,1.0,2500000,Completado,475000.0
46,V046,2026-02-15,Ana Pérez,Pereira,Laptop,Tecnología,1.0,2500000,Completado,475000.0
50,V050,2026-02-19,Laura Torres,bogota,Laptop,Tecnología,1.0,2500000,Completado,475000.0